apiVersion: v1
kind: ConfigMap
metadata:
  name: orders
  labels:
    app.kubernetes.io/name: orders
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: retail-store-sample
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  RETAIL_ORDERS_MESSAGING_PROVIDER: {{ .Values.persistence.messaging | default "in-memory" }}
  RETAIL_ORDERS_PERSISTENCE_PROVIDER: {{ .Values.persistence.provider | default "in-memory" }}
