apiVersion: v1
kind: Secret
metadata:
  name: orders-db
  labels:
    app.kubernetes.io/name: orders
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: retail-store-sample
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  RETAIL_ORDERS_PERSISTENCE_USERNAME: {{ .Values.persistence.dbUser | default "orders" | b64enc }}
  RETAIL_ORDERS_PERSISTENCE_PASSWORD: {{ .Values.persistence.dbPassword | default "qNHkHP8fTr94VI6n" | b64enc }}
