apiVersion: v1
kind: Secret
metadata:
  name: catalog-db
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: retail-store-sample
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  RETAIL_CATALOG_PERSISTENCE_USER: {{ .Values.persistence.dbUser | default "catalog" | b64enc }}
  RETAIL_CATALOG_PERSISTENCE_PASSWORD: {{ .Values.persistence.dbPassword | default "Vxq1xLRUKsYWvb4m" | b64enc }}
